### ISSUE TITLE
Details on pre-processing

### ISSUE THREAD

**Issue by feralvam** [cocoxu/simplification#10]
Hello,

Could you provide details on the pre-processing applied to the dataset? For example, which tokenizer was used (with which options)? Thank you.

**Comment by cocoxu** [comment]
I added the scripts I used for preprocessing into the repository (most were adapted from Moses, I think).

**Comment by feralvam** [comment]
Thanks

**Comment by feralvam** [comment]
Hi,
What was used to truecase the files? Or are those the original sentences before being pre-processed with the scripts?

**Comment by cocoxu** [comment]
I believe they are the original sentences.
