### ISSUE TITLE
Is your project generating paraphrases from the given sentence?

### ISSUE THREAD

**Issue by JafferWilson** [cocoxu/simplification#2]
I would like to know whether your project is just comparing the paraphrases or is generating the paraphrases?
Kindly, guide me.

**Comment by JafferWilson** [comment]
I think this is another waste of time repository. PLease do not waste time here. The author is not even taking care of the issues raised here.

**Comment by cocoxu** [comment]
At the very beginning in the readme, there is the system description (https://cocoxu.github.io/publications/tacl2016-smt-simplification.pdf). It is a text simplification system that generates paraphrases from the given sentence.

**Comment by JafferWilson** [comment]
@cocoxu  My apologize if I offend you. My intentions were not to harm. Thank you for your reply.
