### ISSUE TITLE
STAR - corpus-level SARI

### ISSUE THREAD

**Issue by lbercken** [cocoxu/simplification#5]
In the readme it is mentioned

> Note that STAR is corpus-level version of SARI, SARI is sentence-level.

But, I couldn't find information on STAR anywhere. So, how is it calculated or is it simply the mean of all SARI sentence scores?

**Comment by cocoxu** [comment]
The code for STAR is packed in the zip file linked in the README:
 ./ppdb-simplification-release-joshua5.0/joshua/src/joshua/metris/STAR.java 

"./ppdb-simplification-release-joshua5.0.zip (a 281M file) The experiments in our TACL 2016 paper used the Joshua 5.0. Example scripts for training the simplification are under the directory ./bin/. Note that STAR is corpus-level version of SARI, SARI is sentence-level. The joshua_TACL2016.config is also provided -- that is corresponding to the best system in our paper. You may find the Joshua pipeline tutorial useful."

**Comment by cocoxu** [comment]
similar to corpus-based BLEU vs sentence-level BLEU -- it is calculated over all sentences in the corpus (different from simply the mean of all SARI sentence scores).

**Comment by lbercken** [comment]
Thanks for your quick reply!
